import type { Metadata } from "next";
import { Inter, Lato, Bricolage_Grotesque } from "next/font/google";
import "./globals.css";

// const inter = Inter({
//   variable: "--font-inter",
//   weight: ["400", "500", "600", "700", "800", "900"],
//   subsets: ["latin"],
// });
const lato = Lato({
  variable: "--font-lato",
  weight: ["400", "700", "900"],
  subsets: ["latin"],
});

const bricolage = Bricolage_Grotesque({
  variable: "--font-bricolage-grotesque",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lato.variable} ${bricolage.variable} font-sans antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
